name               = "pager-auth"
main               = "index.js"
compatibility_date = "2024-09-23"

[vars]
GITHUB_CLIENT_ID = "Ov23likIP5P2MhK4fp59"

# GITHUB_CLIENT_SECRET must be added as a secret 
# either in Cloudflare dashboard or as a wrangler secret